### ISSUE TITLE
FuseJS/1장 번역

### ISSUE THREAD

**Issue by Hanul** [Realignist/fuse-docs-kr#5]
번역중입니다.

**Comment by DesignOZ** [comment]
모듈 가져오기> 까지 완성하였습니다만 포크만 할줄 알아는 초보라 어떻게 해야될지 모르겠습니다.

**Comment by Hanul** [comment]
허걱 방금 다 번역하였습니다 ㅜㅜ

**Comment by DesignOZ** [comment]
금방 하셨네요...ㅠ 고생하셨습니다..
이리 저리 눌러보다 쓸데없는 커밋만 늘리고있습니다 ㅠㅠ

**Comment by Realignist** [comment]
@DesignOZ 번역을 할 때에는 먼저 Issue에서 다른 분이 번역을 진행중인지 확인을 하고, 만약 없으면 새로 Issue를 등록하고 하시는 것을 권장합니다. 제가 README에 이런 부분을 확실하게 명시를 했어야하는데 그러질 못했네요. 괜히 고생하게 해드린 것 같아서 죄송스럽습니다.

번역이 끝났으니 이 Issue에 대해서는 완료 처리하겠습니다. :D
